version: '3'
services:
  postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: my-diary-user
      POSTGRES_PASSWORD: my-diary-pass
      POSTGRES_DB: my-diary-db
    restart: always
    networks:
      - lesson
networks:
  lesson: